name: DuckWave CI

name: C/C++ CI

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main, dev ]
  schedule:
    - cron: '0 0 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential libncurses5-dev libncursesw5-dev cmake curl

    - name: Install xmake
      run: |
        curl -fsSL https://xmake.io/shget.text | bash
        echo 'export PATH=~/.local/bin:$PATH' >> ~/.profile
        source ~/.profile

    - name: Install xxHash
      run: |
        git clone https://github.com/Cyan4973/xxHash.git
        cd xxHash
        make
        sudo make install
        cd ..

    - name: Install mold linker
      run: |
        MOLD_VERSION="2.32.1"
        curl -LO https://github.com/rui314/mold/releases/download/v${MOLD_VERSION}/mold-${MOLD_VERSION}-x86_64-linux.tar.gz
        tar -xzf mold-${MOLD_VERSION}-x86_64-linux.tar.gz
        sudo cp mold-${MOLD_VERSION}-x86_64-linux/bin/* /usr/local/bin/
        sudo cp -r mold-${MOLD_VERSION}-x86_64-linux/lib/* /usr/local/lib/
        sudo cp -r mold-${MOLD_VERSION}-x86_64-linux/include/* /usr/local/include/
        sudo cp -r mold-${MOLD_VERSION}-x86_64-linux/share/* /usr/local/share/

    - name: Configure xmake with mold linker
      run: xmake f --toolchain=dwtc --plat=linux --arch=x86_64

    - name: Build project
      run: xmake build