name: C/C++ CI

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main, dev ]
  schedule:
    - cron: '0 0 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential libncurses5-dev libncursesw5-dev cmake

    - name: Install xmake
      run: |
        curl -fsSL https://xmake.io/shget.text | bash

    - name: Install xxHash
      run: |
        git clone https://github.com/Cyan4973/xxHash.git
        cd xxHash
        make
        sudo make install
        cd ..

    - name: Install mold linker
      run: |
        git clone https://github.com/rui314/mold.git
        cd mold
        git checkout v1.0.0  # Replace with the desired version
        make -j$(nproc) CXX=g++
        sudo make install
        cd ..

    - name: Configure xmake with mold linker
      run: xmake f --ld=mold --plat=linux --arch=x86_64

    - name: Build project
      run: xmake build

    - name: Run tests (if applicable)
      run: xmake run duckwave
# 
