name: C/C++ CI

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main, dev ]
  schedule:
    - cron: '0 0 * * *'

jobs:
  build:
    runs-on: fedora-40

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        sudo dnf update -y
        sudo dnf install -y \
          @development-tools \
          ncurses-devel \
          cmake \
          curl \
          mold \
          xmake \
          xxhash-devel

    - name: Configure xmake with mold linker
      run: xmake f --toolchain=dwtc --plat=linux --arch=x86_64

    - name: Build project
      run: xmake build


